name: CI/CD Test

on:
  push:
    branches: ["main"]

jobs:
  # Name of the job/test
  api_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Install Newman
        run: npm install -g newman
      - name: Install dotnet project dependencies
        run: cd "CRM System/server" && dotnet restore
      - name: Build
        run: cd "CRM System/server" && dotnet build
      - name: Start Server
        run: cd "CRM System/server" && nohup dotnet run --project server.csproj &
      - name: Run API-Tests
        run: newman run "./api-tester/Tests For CRM System.postman_collection.json"

  gui_tests:
    runs-on: ubuntu-latest
    needs: api_tests
    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Install dotnet project dependencies
        run: cd E2ETesting-main && dotnet restore E2ETesting.csproj
      - name: Build/Restore Playwright Project
        run: cd E2ETesting-main && dotnet build E2ETesting.csproj
      - name: Ensure browsers are installed
        run: cd E2ETesting-main && pwsh bin/Debug/net8.0/playwright.ps1 install --with-deps
      - name: Start server
        run: cd "CRM System/server" && nohup dotnet run --project server.csproj &
      - name: Run GUI-tests
        run: cd E2ETesting-main && dotnet test E2ETesting.csproj



  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest
    needs: [api_tests, gui_tests] # Kör endast om alla tidigare tester är OK
    steps:
      - name: Deploy App
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: | 
            cd /srv/www/malmo/genc # första gången
            cd /srv/www/malmo/genc/CRM-SYSTEM-Testning # andra gången 
            git clone https://github.com/Genc98/CRM-SYSTEM-Testning.git # första gången
            git pull # andra gången

    

 
