name: CI/CD Test

on:
  push:
    branches: ["main"]

jobs:
 
  gui_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Install dotnet project dependencies
        run: dotnet restore
      - name: Build/Restore Playwright Project
        run: cd E2ETesting-main && dotnet build
      - name: Ensure browsers are installed
        run: cd E2ETesting-main && pwsh bin/Debug/net8.0/playwright.ps1 install --with-deps
      - name: Start server
        run: cd server && nohup dotnet run &
      - name: Run GUI-tests
        run: cd  E2ETesting-main && dotnet test

 
